management:
  security:
    enabled: false
    
server:
  port: 8090
  
spring:
  datasource:
    initialize: true # 운영단에서는 false로 지정 
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:moviedb
    username: sa
    password: null
  h2:
    console:
      enabled: true